### ISSUE TITLE
Widgets, where art thou?

### ISSUE THREAD

**Issue by kwight** [Automattic/Picard#17]
Leading on from #15 , displaying widgets in an API-based theme is currently problematic, as widgets are not available in either the `wpcom` nor WP-API APIs.

Since widgets are all very similar class extensions, one approach would be to take a simple widget, come up with a template, and then use that general template as a base for other widgets in a new endpoint.

Of course, the best first course of action would be finding out what previous work/discussion (if any) have happened at Automattic and in the WP-API project.

**Comment by kwight** [comment]
Any support for widgets will go in a separate plugin, and not in Picard itself; closing.

**Comment by martin-pettersson** [comment]
I have created a plugin: [WP REST API Sidebars](https://github.com/martin-pettersson/wp-rest-api-sidebars) that currently enables read access to sidebars and their widgets. In case it is of use to anyone.
