### ISSUE TITLE
 Fatal error: Class 'WP_JSON_Comments' not found...

### ISSUE THREAD

**Issue by MickeyKay** [Automattic/Picard#43]
Just followed all of the install instructions laid out in the readme file, however upon activating the theme this is what I see:

```
Fatal error: Class 'WP_JSON_Comments' not found in /srv/www/wordpress-trunk/wp-content/themes/Picard/functions.php on line 163
```

I do have the REST API plugin installed, so I don' t think that's the issue. . .

Here's the terminal record of the `gulp build` process:

```
› gulp build
[09:15:28] Warning: gulp version mismatch:
[09:15:28] Global gulp is 3.9.0
[09:15:28] Local gulp is 3.8.11
[09:15:29] Using gulpfile ~/vagrant-local/www/wordpress-trunk/wp-content/themes/Picard/gulpfile.js
[09:15:29] Starting 'styles'...
[09:15:29] Finished 'styles' after 271 ms
[09:15:29] Starting 'scripts'...
[09:15:31] Finished 'scripts' after 1.74 s
[09:15:31] Starting 'build'...
[09:15:31] Finished 'build' after 4.73 μs
```

Any ideas?

**Comment by deadlyhifi** [comment]
Just experimenting and had the same issue. Commented out 
`add_action( 'wp_json_server_before_serve', 'picard_api_init' );` and the class itself, which allowed the site to load but got "Invalid Date". I'm new to React so not sure where to go next.

**Comment by deadlyhifi** [comment]
[Picard/issues/33#issuecomment-139543676](https://github.com/Automattic/Picard/issues/33#issuecomment-139543676) states 

> […] we're going to rework Picard in the coming weeks so that it's compatible with v2 of the REST API.

I'm using v2 of the rest api (2.0-beta4) so perhaps that's the issue.

**Comment by karmatosed** [comment]
@deadlyhifi it will be. I can replicate that error using the v2 plugin.

**Comment by MickeyKay** [comment]
Ah, this theme is built to use v1 of the REST API?

**Comment by kwight** [comment]
@MickeyKay Correct, but there's a PR we're working on for v2 support: #37.
