### ISSUE TITLE
Node-sass compile error on windows

### ISSUE THREAD

**Issue by viankakrisna** [Automattic/Picard#45]
Well, this is not necessarily Picard issue, but is there any downsides to use gulp-sass rather than node-sass?

**Comment by adiardana** [comment]
try this http://stackoverflow.com/a/32946197/975983

work for me.

**Comment by bskimball** [comment]
I can confirm that adiardana's this solution works

**Comment by viankakrisna** [comment]
Thanks! should I close this issue or just leave it for other people to see?

**Comment by adiardana** [comment]
@viankakrisna you should close this issue, it will easier to other people to found.
