### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hasClass' of null

### ISSUE THREAD

**Issue by ghoshnirmalya** [Automattic/Picard#51]
I'm getting this error on line 88 of picard.js

`(if ( ( document.querySelector( 'body' ).hasClass( 'page' ) || document.querySelector( 'body' ).hasClass( 'single' ) ) && document.querySelector( '.hentry' ).hasClass( 'has-post-thumbnail' ) ) {)`

**Comment by denishue** [comment]
Same here ! Did you solve the issue ?

Uncaught TypeError: Cannot read property 'hasClass' of null

**Comment by ghoshnirmalya** [comment]
@denishue No, I couldn't resolve the issue.

**Comment by denishue** [comment]
picard.js?ver=20150506:88 Uncaught TypeError: Cannot read property 'hasClass' of nullentry_thumbnail @ picard.js?ver=20150506:88Content_componentDidMount @ picard.js?ver=20150506:41assign.notifyAll @ picard.js?ver=20150506:2292ON_DOM_READY_QUEUEING.close @ picard.js?ver=20150506:15284Mixin.closeAll @ picard.js?ver=20150506:18642Mixin.perform @ picard.js?ver=20150506:18583Mixin.perform @ picard.js?ver=20150506:18569assign.perform @ picard.js?ver=20150506:16723(anonymous function) @ picard.js?ver=20150506:16802ReactUpdates_flushBatchedUpdates @ picard.js?ver=20150506:14541Mixin.closeAll @ picard.js?ver=20150506:18642Mixin.perform @ picard.js?ver=20150506:18583ReactDefaultBatchingStrategy.batchedUpdates @ picard.js?ver=20150506:10750enqueueUpdate @ picard.js?ver=20150506:16844ReactCompositeComponentMixin.replaceState @ picard.js?ver=20150506:8267ReactCompositeComponentMixin.setState @ picard.js?ver=20150506:8239(anonymous function) @ picard.js?ver=20150506:588Request.callback @ picard.js?ver=20150506:22381(anonymous function) @ picard.js?ver=20150506:22096Emitter.emit @ picard.js?ver=20150506:741xhr.onreadystatechange @ picard.js?ver=20150506:22463

here is complete console error log
